language: node_js

sudo: required

node_js:
    - v10.8.0

cache:
    directories:
        - node_modules

notifications:
    email:
        on_success: never
        on_failure: always

script:
    - npm install
    - npm run lint
    - npm run build
    - npm link
    - nqr -c conf.yml -l `pwd`
    - node_modules/.bin/html5v output.html
